package:
  name: simtree
  version: "0.2.3"

source:
   - path: ../

build:
   noarch: python
   number: 0
   script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip

  run:
    - python
    - matplotlib>=3.1.3
    - numpy>=1.15.2
    - pandas>=0.19.2
    - scikit-learn>=0.23.0
    - r-base
    - r-bigsplines==1.1_1
    - rpy2>=3.3.6

tests:
  imports:
    - simtree 

about:
  home: https://github.com/ZebinYang/simtree 
  license: GPL 
  summary: Single-Index Model Tree
